server:
  port: 8080

# Mongo
spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      auto-index-creation: true
      authentication-database: admin
      database: circuit-breaker

# Feign Client
comment:
  service:
    url: http://localhost:8082/api/v1/comments

# Resilience4j
resilience4j.circuitbreaker:
  instances:
    comments:
      sliding-window-size: 4
      automatic-transition-from-open-to-half-open-enabled: true
      minimum-number-of-calls: 4
      permitted-number-of-calls-in-half-open-state: 2
      wait-duration-in-open-state: 10s
      # slow-call-duration-threshold: 1000
      # slow-call-rate-threshold: 10.0
